

CREATE NONCLUSTERED INDEX ConferenceBooking-ConferenceIDIndex ON ConferenceBooking
   (
    ConferenceID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX ConferenceBookingClientIDIndex ON ConferenceBooking
(
[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX ConferenceDayBookingConfBookingIDIndex ON ConferenceDayBooking
   (
    ConferenceBookingID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX ConferenceDayBookingConferenceDayIDIndex ON ConferenceDayBooking
   (
    ConferenceDayID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)




CREATE NONCLUSTERED INDEX ConferenceDayParticipantsParticipantIDIndex ON ConferenceDayParticipants
   (
    ParticipantID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX ConferenceDayParticipantsConferenceDayBookingIDIndex ON
   ConferenceDayParticipants
       (
        ConferenceDayBookingID ASC
           ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX StudentsStudentID ON Student
   (
    StudentID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX PaymentsConferenceBookingIDIndex ON Payments
   (
    ConferenceBookingID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX WorkshopParticipantsWorkshopBookingIDIndex ON
   WorkshopParticipants
       (
        WorkshopBookingID ASC
           ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX WorkshopParticipantsConferenceDayParticipantIDIndex ON
   WorkshopParticipants
       (
        ConferenceDayParticipantID ASC
           ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX WorkshopsConferenceDayIDIndex ON Workshops
   (
    ConferenceDayID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX WorkshopsBookingConferenceDayBookingIDIndex ON WorkshopsBooking
   (
    ConferenceDayBookingID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX WorkshopsBookingWorkshopIDIndex ON WorkshopsBooking
   (
    WorkshopID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



CREATE NONCLUSTERED INDEX CompaniesClientIDIndex ON Companies
   (
    ClientID ASC
       ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF,
   ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
